groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'


urlpatterns = [
    path('', views.ListGroup.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<str:slug>', views.SingleGroup.as_view(), name='single'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(), name='leave'),
    path('join/<str:slug>/', views.JoinGroup.as_view(), name='join'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.Test.as_view(), name='test'),
    path('thanks/', views.Thanks.as_view(), name='thanks'),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

groups/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify
# import misaka
from django import template

register = template.Library()

User = get_user_model()


class Group(models.Model):
    name = models.CharField(unique=True, max_length=255)
    slug = models.SlugField(unique=True, allow_unicode=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(blank=True, default='', editable=False)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        # self['description_html'] = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ['user', 'group']

groups/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Group, GroupMember
from django.urls import reverse
from django.contrib import messages
from django.db import IntegrityError


class SingleGroup(generic.DetailView):
    model = Group


class ListGroup(generic.ListView):
    model = Group


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    model = Group
    fields = ('name', 'description')


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get("slug"))
        print(group)
        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, "Warning, You are already member of {}".format(group.name))
        except Exception as e:
            print(str(e))
        else:
            messages.success(self.request, "You are now member of {} group".format(group.name))
        return super().get(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug': self.kwargs.get("slug")})


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = GroupMember.objects.filter(user=self.request.user, group__slug=self.kwargs.get('slug'))
        except GroupMember.DoesNotExist:
            messages.warning(self.request, "You cannot leave this group, because you are not a part of this")
        else:
            membership.delete()
            messages.success(self.request, "You are successfully left the group")
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <h1>{{group.name}}</h1>
    <h2>Member Count: {{group.members.count}}</h2>
    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">Join</a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    <div class="col-md-8">
        {% if group.posts.count == 0 %}
            <h2>No Posts in this group</h2>
        {% else %}
            {% for post in group.posts.all %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
    <div class="col-md-4">
        <h4>Create New Group</h4>
    </div>
    <div class="col-md-6">
        <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create" class="btn btn-primary btn-large">
        </form>
    </div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <div class="col-md-4">
        <div class="content">
            {% if user.is_authenticated %}
                <h2>
                    Welcome back
                    <a href="{% url 'groups:all' %}">@{{user.username}}</a>
                </h2>
            {% else %}
                <h2>
                    <p>
                        Welcome to group page! Select a Group with a shared interest!
                    </p>
                </h2>
            {% endif %}
        </div>
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">Create New Group</a>
    </div>
{% endblock %}


{% block group_content %}
    <div class="col-md-8">
        <div class="list-group">
            {% for group in object_list %}
            <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
                <h3 class="title list-group-item-heading">{{group.name}}</h3>
                <div class="list-group-item-text container-fluid">
                    {{group.description|safe}}
                    <div class="row">
                        <div class="col-md-4">
                            <span class="badge">{{group.members.count}}</span>member{{group.members.count|pluralize}}
                        </div>
                        <div class="col-md-4">
                            <span class="badge">{{group.posts.count}}</span>Post{{group.posts.count|pluralize}}
                        </div>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}