groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'


urlpatterns = [
    path('', views.ListGroup.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<str:slug>', views.SingleGroup.as_view(), name='single'),
    path('leave/<str:slug>/', views.LeaveGroup.as_view(), name='leave'),
    path('join/<str:slug>/', views.JoinGroup.as_view(), name='join'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPost.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.Test.as_view(), name='test'),
    path('thanks/', views.Thanks.as_view(), name='thanks'),
    path('groups/', include('groups.urls')),
    path('posts/', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from groups.models import Group
# import misaka

User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    created_at = models.DateTimeField(auto_now=True)
    group = models.ForeignKey(Group, related_name='posts', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username, 'pk': self.pk})

    # def save(self, *args, **kwargs):
    #     self.message_html = misaka.html(self.message)
    #     super().save(*args, **kwargs)

    class Meta:
        unique_together = ['user', 'message']
        ordering = ['-created_at']

posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, DeleteView, ListView, RedirectView
from django.contrib.auth import get_user_model
from braces.views import SelectRelatedMixin
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post

User = get_user_model()


class PostList(SelectRelatedMixin, ListView):
    model = Post
    select_related = ('user', 'group')


class UserPost(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, DetailView):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super(PostDetail, self).get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    model = Post
    fields = ('message', 'group')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeleteView(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
{% load ui_helper %}
{% load tz %}
<div class="post media">
	<h3>{{ post.message|safe }}</h3>
	<div class="media-body">
		<strong>{{ post.user.username }}</strong>
		<h5 class="media-heading">
			<span class="username">
				<a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
			</span>
			:
			<time class="time">
				<a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at|timeconvert|localtime }}</a>
			</time>
			{% if post.group %}
			<span class="group-name">in <a href="#">{{ post.group.name }}</a></span>
			{% endif %}
		</h5>




		<div class="media-footer">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="posts-page">
        <div class="container">
            <div class="row">
                {% block prepost %}{% endblock %}
                {% block post_content %}{% endblock %}
                {% block post_post %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
    <div class="col-md-8">
        {% include 'posts/_post.html' %}
    </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap4 %}

{% block post_content %}
	<div class="col-md-4">
		<h4>Create New Post</h4>
	</div>
	<div class="col-md-8">
		<form method="POST" action="{% url 'posts:create' %}" id="postForm">
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" value="Post" class="btn btn-primary btn-large">
		</form>
	</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load static %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">

				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>




		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h5>@{{ post_user.username }}</h5>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}